select 
DATEPART(YEAR,DATE_) as YEAR_,
DATEPART(MONTH,DATE_) as MONTH_,

case 
	when PAYMENTTYPE = 1 THEN 'KREDİ KARTI'
	when PAYMENTTYPE = 2 THEN 'BANKA HAVALESİ'
END AS ÖDEME_YÖNTEMİ,
SUM(PAYMENTTOTAL) AS TOPLAM_TUTAR
from PAYMENTS

GROUP BY DATEPART(YEAR,DATE_),PAYMENTTYPE,DATEPART(MONTH,DATE_)
ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_)
